title: "Kiwi's House"
description: "Kiwi's Blog"
url: 
baseurl: ""
author: "moeKiwiSAMA"
paginate: 5
paginate_path: "/blog/page:num/"


# Build settings
theme: jekyll-theme-mdui
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed

exclude:
  - package.json
  - node_modules
  - gulpfile.js
  - Gemfile
  - Gemfile.lock
  - jekyll-theme-mdui.gemspec
  - LICENSE.txt
  - README.md
  - vendor
