head: 
   favicon: "https://i.loli.net/2018/12/14/5c135b73215cf.png" #  the favicon
   high_res_favicon: "https://i.loli.net/2018/12/14/5c135b73215cf.png" #  the favicon using high quality format
   apple_touch_icon: "https://i.loli.net/2018/12/14/5c135b73215cf.png" # the iOS Home button icon
   keywords: "blog jekyll mdui theme kiwi moekiwisama" #  the site keywords

uiux:
   android_chrome_color: "#2196f3" #  the color of the Chrome address bar
   nprogress_color: "#29d" #  the color of the top loading progress bar
   nprogress_buffer: 200 # the top loading progress bar buffers
   meng: true

background: 
   purecolor: "#eeeeee" # the background color

img: 
   avatar: "https://i.loli.net/2018/12/14/5c135b8959a6f.png" # your avatar

card: 
   card_shadow: 1 # card shadow (0-24), 0 is not displayed
   card_hoverable: false # When the hover to deepen the shadowf

many_authors: false

sns_share: # SNS Share Switch
   twitter: true
   facebook: true
   googleplus: true
   weibo: true
   linkedin: true
   qq: true
   telegram: true

comment:
  used: "disqus" # disqus,livere,gitment,valine
  # disqus config
  disqus_shortname: "nyan-kiwi-cat" # Your disqus 
  disqus_button: true # disqus load button
  disqus_proxy: false # # disqus proxy(Do not use)
  disqus_proxy_url: "" # (Do not use)
  disqus_api_key: "" # (Do not use)
  # livere config 
  livere_type: 'city'
  livere_data_uid: ''
  # gitment config
  owner: ""
  repo: ""
  client_id: ""
  client_secret: ""
  #valine config
  valine_app_id: ''
  valine_app_key: ''
  valine_placeholder: "ヾﾉ≧∀≦)o来啊，快活啊!"

prism:
  themes: prism-okaidia
  components: 
    - bash 
    - go
    - rust
    - python
  plugins: 

google_analytics: "UA-129419173-1"  # google analytics code

lang: "en-US"  # lang

deploy: "" # if you used coding pages

custom_css: "" # Use the assets/css/customCss.css

custom_js: "" # Use the assets/js/customJS.js
